- name: Hold ufw
  ansible.builtin.dpkg_selections:
    name: ufw
    selection: hold

# Upgrade RHEL family OS packages
- name: Upgrade RHEL Family OS packages
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"

- name: Update apt-get repo and cache (обноваление операционной системы)
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600    
  when: ansible_os_family == "Debian"

- name: Remove old kernels
  shell: "rpm -q kernel | grep -v `uname -r` | grep -v `/sbin/grubby --default-kernel | sed -r 's#^/boot/vmlinuz-##'` | xargs rpm -e || true"