# Не обновлять один из пакеов
- name: Hold ufw
  ansible.builtin.dpkg_selections:
    name: ufw
    selection: hold

# Обновить пакеты rhel ос 
- name: Upgrade RHEL Family OS packages
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"

# Обновить пакеты debian ос 
- name: Update apt-get repo and cache (обноваление операционной системы)
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600    
  when: ansible_os_family == "Debian"

# Удалить все кроме двух версий ядра
- name: Remove old kernels
  shell: "apt-get --purge remove $(dpkg --list | grep -E -i 'linux-image|linux-headers' | head -n -3)"